import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import axios from "axios";
import ToastProviders from "@/providers/ToastProviders";
import ModalProviders from "@/providers/ModalProviders";

export const metadata: Metadata = {
  title: "Amen Bank",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  axios.defaults.baseURL = "http://localhost:10000/";

  return (
    <html lang="en">
      <body className="">
        {children}
        <ToastProviders />
        <ModalProviders />
      </body>
    </html>
  );
}
