import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";

import ToastProviders from "@/providers/ToastProviders";
import ModalProviders from "@/providers/ModalProviders";
import ThemesProviders from "@/providers/ThemesProviders";
import ThemeButton from "@/components/shared/ThemeButton";
import NextIntlProvider from "@/providers/NextIntlProvider";
import { getSession } from "@/lib";
import { redirect } from "next/navigation";
import ReactQueryProvider from "@/providers/QueryClientProvider";

// export const metadata: Metadata = {
//   title: "",
//   description: "Generated by create next app",
// };
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Amen Bank",
  description: "PWA application with Next 13",
  generator: "Next.js",
  manifest: "/manifest.json",
  keywords: ["nextjs", "nextjs13", "next13", "pwa", "next-pwa"],
  themeColor: [{ media: "(prefers-color-scheme: dark)", color: "#fff" }],
  authors: [
    { name: "Rajesh Prajapati" },
    {
      name: "Rajesh Prajapati",
      url: "https://www.linkedin.com/in/raazeshp96/",
    },
  ],
  viewport:
    "minimum-scale=1, initial-scale=1, width=device-width, shrink-to-fit=no, viewport-fit=cover",
  icons: [
    { rel: "apple-touch-icon", url: "icons/icon-128x128.png" },
    { rel: "icon", url: "icons/icon-128x128.png" },
  ],
};
export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  let messages;
  try {
    messages = (await import(`../../messages/${locale}.json`)).default;
  } catch (error) {
    console.error("Failed to load messages:", error);
  }

  const session = await getSession();

  return (
    <html lang={locale}>
      <body className="min-h-screen">
        <NextIntlProvider locale={locale} messages={messages}>
          <ThemesProviders>
            <ReactQueryProvider>{children}</ReactQueryProvider>
            <ToastProviders />
            <ModalProviders />
          </ThemesProviders>
        </NextIntlProvider>
      </body>
    </html>
  );
}
