import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import axios from "axios";
import ToastProviders from "@/providers/ToastProviders";
import ModalProviders from "@/providers/ModalProviders";
import ThemesProviders from "@/providers/ThemesProviders";
import ThemeButton from "@/components/shared/ThemeButton";
import NextIntlProvider from "@/providers/NextIntlProvider";
import { getSession } from "@/lib";
import { redirect } from "next/navigation";
import ReactQueryProvider from "@/providers/QueryClientProvider";

export const metadata: Metadata = {
  title: "Amen Bank",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  let messages;
  try {
    messages = (await import(`../../messages/${locale}.json`)).default;
  } catch (error) {
    console.error("Failed to load messages:", error);
  }

  const session = await getSession();

  return (
    <html lang={locale}>
      <body className="min-h-screen">
        <NextIntlProvider locale={locale} messages={messages}>
          <ThemesProviders>
            <ReactQueryProvider>{children}</ReactQueryProvider>
            <ToastProviders />
            <ModalProviders />
          </ThemesProviders>
        </NextIntlProvider>
      </body>
    </html>
  );
}
