import { Agence } from "./agence.model";
import { Zone } from "./zone.model";

export interface client{
    fc:                        null | string;
    sd:                        string;
    act:                       string;
    cli:                       string;
    nom:                       string;
    obs:                       null;
    seg:                       string;
    tel:                       string;
    trt:                       null | string;
    catl:                      string;
    mott:                      null | string;
    sort:                      null;
    tel1:                      string;
    tel2:                      null;
    tel3:                      null;
    motif:                     null;
    phase:                     string;
    trf_a:                     null | string;
    trf_c:                     null;
    trt_d:                     null;
    agence:                    number;
    classe:                    number;
    groupe:                    number;
    motstr:                    null;
    prol_c:                    null | string;
    region:                    string;
    trt_fc:                    null;
    encours:                   null;
    max_nbj:                   number;
    mnt_imp:                   string;
    score_c:                   null;
    susp_cc:                   null | string;
    susp_lr:                   null;
    trf_c_d:                   null;
    trf_ctx:                   null;
    trt_adm:                   null;
    trt_agc:                   null;
    trt_div:                   null;
    trt_dos:                   null;
    trt_dre:                   null;
    trt_ext:                   null;
    trt_grp:                   null;
    trt_plr:                   null;
    trt_rec:                   null;
    trt_reg:                   null;
    trt_rer:                   null;
    trt_res:                   null;
    trt_sog:                   null;
    trt_tak:                   null;
    trt_tar:                   null;
    code_aff:                  string;
    code_rec:                  null | string;
    date_lmd:                  null;
    etat_lmd:                  null;
    flag_sms:                  null;
    flag_trt:                  string;
    huissier:                  null;
    nbre_imp:                  number;
    prol_v_c:                  null;
    score_re:                  null;
    susp_crd:                  null;
    susp_sms:                  null;
    trf_attr:                  null;
    trt_call:                  null;
    codesuivi:                 string;
    date_prol:                 Date | null;
    date_susp:                 null;
    etat_scan:                 null;
    reaff_str:                 null;
    susp_lmd1:                 null;
    susp_lmd2:                 null;
    susp_somm:                 null;
    trf_ctx_v:                 null;
    trt_adm_d:                 null;
    trt_agc_d:                 null;
    trt_chcom:                 null;
    trt_div_d:                 null;
    trt_dos_d:                 null;
    trt_dre_d:                 null;
    trt_grp_d:                 null;
    trt_mecom:                 null;
    trt_plr_d:                 null;
    trt_rec_d:                 null;
    trt_reg_d:                 null;
    trt_rer_d:                 null;
    trt_suivi:                 null;
    date_carte:                null;
    date_trf_c:                null;
    eng_direct:                number;
    engagement:                string;
    etat_carte:                null;
    etat_scan2:                null;
    motif_som1:                null;
    motif_som2:                null;
    phase_init:                null;
    prop_conso:                null;
    recouvreur:                null;
    trt_call_d:                null;
    arrengement:               null;
    classe_prec:               null;
    code_engage:               string;
    date_prol_v:               null;
    depassement:               string;
    etat_lettre:               null;
    flg_trf_ctx:               null;
    prop_valide:               null;
    susp_valide:               null;
    tot_creance:               string;
    trf_propose:               null | string;
    trt_chcom_d:               null;
    trt_cnx_sog:               null;
    trt_mecom_d:               null;
    trt_suivi_d:               null;
    type_client:               string;
    confirmation:              null;
    date_collect:              null;
    date_trf_ctx:              null;
    etat_pv_som1:              null;
    etat_pv_som2:              null;
    flag_collect:              null;
    flg_stk_prol:              null;
    marge_prol_c:              number | null;
    marge_prol_d:              null;
    motif_prol_c:              null;
    motif_prol_d:              null;
    nombre_jours:              number;
    prop_susp_cc:              null | string;
    prop_susp_lr:              null;
    susp_propose:              null;
    trt_call_rec:              null;
    trt_call_sog:              null;
    valid_prol_d:              null;
    code_aff_init:             null;
    date_conf_dos:             null;
    date_trf_attr:             null;
    date_trfa_ctx:             null;
    etat_scan_ctx:             null;
    etat_scan_dos:             null | string;
    flag_scan_dos:             null;
    matricule_ctx:             null;
    motif_trf_ctx:             null;
    prop_susp_crd:             null;
    prop_susp_sms:             null;
    susp_modifier:             null;
    trf_dynamique:             null;
    trf_propose_v:             null | string;
    valid_strat_d:             null;
    date_aff_huiss:            null;
    date_conf_som1:            null;
    date_conf_som2:            null;
    date_prop_prol:            null;
    date_prop_susp:            null;
    matricule_attr:            null;
    matricule_susp:            null;
    motif_scan_ctx:            null;
    prol_propose_c:            null | string;
    prol_propose_d:            null;
    prop_susp_lmd1:            null;
    prop_susp_lmd2:            null;
    prop_susp_somm:            null;
    trt_cnx_sog_cc:            null;
    date_prop_conso:           null;
    date_sommation1:           null;
    date_sommation2:           null;
    date_trfa_ctx_c:           null;
    etat_recouvreur:           null | string;
    matricule_conso:           null;
    matricule_trf_c:           null;
    strat_propose_d:           null;
    trf_contentieux:           null;
    trf_ctx_propose:           null;
    trt_cnx_sog_dir:           null;
    trt_cnx_sog_div:           null;
    confirmation_ctx:          null;
    date_prop_prol_d:          null;
    date_trf_propose:          Date | null;
    lettre_employeur:          null;
    matricule_lettre:          null;
    matricule_prol_c:          null | string;
    nombre_jours_sdb:          number;
    date_conf_trf_ctx:         null;
    date_prop_strat_d:         null;
    date_reaf_strat_d:         null;
    date_valid_prol_d:         null;
    lettre_sommation1:         null;
    lettre_sommation2:         null;
    matricule_collect:         null;
    matricule_trf_ctx:         null;
    prop_modification:         null;
    date_lettre_recouv:        null;
    date_trf_propose_v:        Date | null;
    date_valid_strat_d:        null;
    matricule_prol_c_v:        null;
    date_aff_recouvreur:       Date | null;
    matricule_prop_susp:       null;
    matricule_trf_ctx_c:       null;
    date_prop_modif_susp:      null;
    matricule_affect_rec:      null;
    montant_autorisation:      null | string;
    date_lettre_employeur:     null;
    matricule_prop_prol_c:     null;
    matricule_prop_prol_d:     null;
    matricule_trf_propose:     null | string;
    matricule_affect_huiss:    null;
    matricule_prop_strat_d:    null;
    matricule_reaf_strat_d:    null;
    matricule_valid_prol_d:    null;
    matricule_trf_propose_v:   null | string;
    matricule_valid_strat_d:   null;
    matricule_prop_modif_susp: null;
    id:                        string;
    created_at:                Date;
    updated_at:                Date;
    Agence:                    Agence;
    Zone:                      Zone;
}